### ISSUE TITLE
Install PHP extensions

### ISSUE THREAD

**Issue by sestrella** [CircleCI-Public/php-orb#33]
Installing language extensions is a quite common task in PHP projects since some frameworks and libraries rely on that. A simple custom command in conjunction with `install-php` gets the job done, however, it is more prone to errors during a PHP upgrade process. Consider the following example:

```yml
- php/install-php:
    install-version: 7.4
- run: sudo apt-get install -y php7.4-bz2 php7.4-pgsql
```

It's more likely to forget to upgrade an extension compared with the following code snippet where the PHP version is only specified once and the command takes care of choosing the right package name:

```yml
- php/install-php:
    install-version: 7.4
    extensions: ["bz2", "pgsql"]
```

If the idea of introducing an `extensions` parameter in the context of `install-php` commands makes sense, I would be more than happy to submit a PR adding this feature.

**Comment by kevin-kortum-trustedshops** [comment]
Really want that for my pipeline. Current workaround

```yaml
      - php/install-php:
          version: "8.2"
      - run:
          name: Install PHP Extensions
          command: |
            sudo add-apt-repository ppa:ondrej/php -y
            sudo apt update
            sudo apt install -y php8.2-fpm php8.2-phpdbg php8.2-zip php8.2-xml php8.2-dom php8.2-mbstring libpcre2-8-0
```
